# Site settings
title: Miles' Recepies
email: miles@budden.net
description: My own recepies
baseurl: "milesbudden.com/recepies"
github_username:  pbexe

# Build settings
markdown: kramdown

collections:
  components:
    output: true
  recipes:
    output: true

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
